
server:
  port: 80
    
spring:
  mvc:
    view:
      prefix:
      suffix:
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: Blue8119!
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
        
  spring:
    servlet:
      multipart:
        enabled: true
        max-file-size: 1GB
        max-request-size: 1GB
        file-size-threshold: 0

